id: I476A7A57
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:51:08+00:00'
last_modified: '2022-06-08T07:30:28.284957+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9279
  title: གསང་སྔགས་སྔ་འགྱུར་གྱི་བསྟན་འཛིན་སྐྱེས་མཆོག་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    92AA:
      image_group_id: I1KG9346
      title: ''
      total_pages: 114
      order: 1
      base_file: 92AA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
