id: P006876
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:28:05.776579
source_metadata:
  id: bdr:W1KG9279
  title: གསང་སྔགས་སྔ་འགྱུར་གྱི་བསྟན་འཛིན་སྐྱེས་མཆོག་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    39575ca4a54b48abbe634e2dd9a94c29:
      image_group_id: I1KG9346
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
