id: P006876
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9279
  title: གསང་སྔགས་སྔ་འགྱུར་གྱི་བསྟན་འཛིན་སྐྱེས་མཆོག་རིམ་བྱོན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    39575ca4a54b48abbe634e2dd9a94c29:
      image_group_id: I1KG9346
      title: ''
      volume_number: 1
      total_pages: 114
